public class MyFirstApex {

    Integer mySalary = 10000;
    String EmpName = 'Kuamr';
    static Integer empcount = 100;

    public MyFirstApex()
    {
    
    //My third commit from Vs Code
    }

    //public static Date newInstance(Integer year, Integer month, Integer day)
    //<<Access>> <<static>> <<Return DataType>> 
/*     MyFirstApex myobj1 = new MyFirstApex();
System.debug(myobj1.mySalary);
MyFirstApex myobj2 = new MyFirstApex();
myobj2.mySalary = 20000;
System.debug(myobj2.mySalary);
MyFirstApex.empcount= 100;
System.debug(myobj2.mySalary);
System.debug(MyFirstApex.empcount); */
}


